### ISSUE TITLE
Improvement suggestion: re-export "sub-crates" in features

### ISSUE THREAD

**Issue by Quba1** [LDeakin/zarrs#74]
Newest (unreleased) version have moved some parts of the `zarrs` API into multiple "sub-crates" (`zarrs_storage`, `zarrs_filesystem` etc).

I would like to suggest an improvement for usability: make the `zarrs` crate re-export the "sub-crates" depending on the selected features. 

For example in `Cargo.toml`:
```toml
# Suggested API would look like this:
zarrs = {version="0.17", features=["filesystem"]}

# Instead of this:
zarrs = "0.17"
zarrs_filesystem = "0.1"
```

I believe this change would improve API discoverability and overall intuitiveness, while preserving the new crate structure. And users wouldn't have to worry how what "sub-crate" versions work with the main crate version.

If you find this idea worth implementing I can make a PR for it. Otherwise feel free to close this issue.
